services:
  php:
    image: php-mysql:latest
    ports:
      - "4900:4900"
    depends_on:
      - mysql
    # Wait until MySQL is healthy before starting PHP
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysql:3306"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  mysql:
    image: mysql:8.0  # MySQL version
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  # Expose MySQL on port 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
